# Generated by Django 2.0.3 on 2018-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_date',
            field=models.DateTimeField(verbose_name='Post Date'),
        ),
    ]
