# Generated by Django 2.0.3 on 2018-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180318_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(verbose_name='Post Date'),
        ),
    ]
