# Generated by Django 2.0.3 on 2018-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180319_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Post Date'),
        ),
    ]
